### ISSUE TITLE
wrong accent marks

### ISSUE THREAD

**Issue by kanayamah** [UniversalDependencies/UD_Spanish-GSD#14]
Accent marks are dropped in some sentences, but they are not annotated in lemma.  In the word 19, wrong lemma is given (probably it is wrongly predicted as a plural form of *`adema`).
```
# sent_id = es-dev-003-s429
# text = Este organismo maneja mas de cinco mil empresas privadas, publicas y extranjeras en el territorio chino, ademas de que realiza estudios de mercados, deteccion de nichos de oportunidades y todo lo relacionado con productos carnicos, agricolas y pesqueros.
4	mas	mas	ADV	_	_	6	advmod	_	_
11	publicas	publico	ADJ	_	Gender=Fem|Number=Plur	9	conj	_	_
19	ademas	adema	ADV	_	_	22	advmod	_	_
```

They should have correct lemmata with `CorrectForm` annotation in MISC field.
```
4	mas	más	ADV	_	_	6	advmod	_	CorrectForm=más
11	publicas	público	ADJ	_	Gender=Fem|Number=Plur	9	conj	_	CorrectForm=públicas
19	ademas	además	ADV	_	_	22	advmod	_	CorrectForm=además
```

This is an example of wrong accent mark, which causes a wrong lemma and empty features.
```
# sent_id = es-dev-003-s450
# text = En una taberna escribío lo encontrado y luego huyó al desierto sabiendo que las tropas del Califa le buscaban.
4	escribío	escribío	VERB	_	VerbForm=Fin	0	root	_	_
```
This should be annotated as:
```
4	escribío	escribir	VERB	_	Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin	0	root	_	CorrectForm=escribió
```

**Comment by arademaker** [comment]
You also need the “Typo=Yes” in the features right?

**Comment by kanayamah** [comment]
@arademaker good point, thanks!  
I added `Typo=Yes` in the latest commit (https://github.com/UniversalDependencies/UD_Spanish-GSD/commit/5625865e921164ab33446a24791e52bb78594af9), and sorted FEATS and MISC fields appropriately.

**Comment by AngledLuffa** [comment]
is this fully resolved?
