### ISSUE TITLE
Relative pronouns annotated as mark

### ISSUE THREAD

**Issue by ngiordani** [UniversalDependencies/UD_Spanish-GSD#2]
I noticed a few examples like this when running experiments on Spanish data:

1       Estoy   _       VERB    _       _       4       cop     _       _
2       más     _       ADV     _       _       4       advmod  _       _
3       que     _       CONJ    _       _       2       case    _       _
4       tranquila       _       ADJ     _       _       0       root    _       _
5       cuando  _       SCONJ   _       _       6       mark    _       _
6       dejo    _       VERB    _       _       4       advcl   _       _
7       a       _       ADP     _       _       8       case    _       _
8       Bruc    _       PROPN   _       _       6       dobj    _       _
9       allí    _       ADV     _       _       6       advmod  _       _
10      pues    _       SCONJ   _       _       11      mark    _       _
11      veo     _       VERB    _       _       4       advcl   _       _
12      a       _       ADP     _       _       13      case    _       _
13      Eli     _       PROPN   _       _       11      dobj    _       _
14      y       _       CONJ    _       _       13      cc      _       _
15      Rosa    _       PROPN   _       _       13      conj    _       _
16      que     _       SCONJ   _       _       17      mark    _       _
17      adoran  _       VERB    _       _       13      acl:relcl       _       _
18      los     _       DET     _       _       19      det     _       _
19      animales        _       NOUN    _       _       17      dobj    _       _
20      y       _       CONJ    _       _       13      cc      _       _
21      el      _       DET     _       _       22      det     _       _
22      cariño  _       NOUN    _       _       13      conj    _       _
23     con     _       ADP     _       _       24      case    26      _
**24      que     _       SCONJ   _       _       26      mark    _       _**
25      lo      _       PRON    _       _       26      dobj    _       _
26      tratan  _       VERB    _       _       22      acl:relcl       _       _
27      .       _       PUNCT   _       _       4       punct   _       _

(The giveaway is a mark-labeled node with det- or case-labeled dependents.)

**Comment by jnivre** [comment]
Nice catch! This should definitely be nmod.

**Comment by dan-zeman** [comment]
Thanks, @ngiordani 
We actually have this on the to-do list but it is not sure that we will be able to fix it before the upcoming release.

I also found it the same way as you, i.e. seeing dependents on mark-labeled nodes. But there are other occurrences of _que_ that are tagged `SCONJ/mark` and should be `PRON/nsubj`, `PRON/dobj` etc. These will be more difficult to catch. Perhaps if the parent of _que_ is `acl:relcl`, then _que_ must be pronoun? Example (the first _que_`.SCONJ` I found using PML-TQ):

_... existirá una plataforma que le permitirá ..._

**Comment by ngiordani** [comment]
I think that's right, @dan-zeman. And yes, I think if the parent
is (correctly) acl:relcl labeled, *que* is always a relative pronoun. Or at
least I can't think of a counterexample in Portuguese right now. :) But I'm
actually pretty confident.

If there is a case dependent, it's easy -- relation should be nmod. If
there is no case dependent, you could try looking for a argument: if the
relative clause has a subject, call *que* nsubj; if there's already a
subject, call it *dobj*.

I think this heuristic should work fairly well; I'll try to find some time
this week to test it out for you. (I'm interested in removing all spurious
dependents of function words from the Spanish corpus, for my own selfish
purposes... :))

**Comment by ngiordani** [comment]
.I don't know why, but to me my comment from an hour ago looks truncated (with stuff after the ...), so I'm excluding that and reposting.

I think that's right, @dan-zeman. And yes, I think if the parent
is (correctly) acl:relcl labeled, *que* is always a relative pronoun. Or at
least I can't think of a counterexample in Portuguese right now. :) But I'm
actually pretty confident.

If there is a case dependent, it's easy -- relation should be nmod. If
there is no case dependent, you could try looking for a argument: if the
relative clause has a subject, call *que* nsubj; if there's already a
subject, call it *dobj*.

I think this heuristic should work fairly well; I'll try to find some time
this week to test it out for you. (I'm interested in removing all spurious
dependents of function words from the Spanish corpus, for my own selfish
purposes... :))

**Comment by dan-zeman** [comment]
Closing now. At least the validator would now report mark dependents with their own dependents, so this should be fixed. It is possible though that there are other instances of _que_ that should be pronouns and are annotated as conjunctions.
